version: "3.1"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'